### ISSUE TITLE
Error in Multithreading?

### ISSUE THREAD

**Issue by fischerdom** [wmayner/pyphi#16]
Hey guys,

It seems that pyphi isn't stable anymore. I got a multithreading exception:

`Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/queues.py", line 242, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/usr/lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)`

Could you maybe help me with this issue?

**Comment by wmayner** [comment]
Hi Dominik,

This should have been fixed a few days ago. What commit of the `develop` branch are you on? Try updating to the latest commit and see if the problem still comes up.

Cheers,
Will

**Comment by rlmv** [comment]
Yes, @fischerdom this should be resolved with the latest code. Please let us know if this shows up again and I'll investigate further.

**Comment by fischerdom** [comment]
Hey, 

many thanks for the answer. Yes it was an older version. I will make an update and tell you if the exception still occurs.


Cheers 
Dom

**Comment by fischerdom** [comment]
Unfortunately, I still get the exception. Somehow on a random manner. 

I removed the package via pip and reinstalled it, before...

**Comment by rlmv** [comment]
Interesting. And this is with the head of the develop branch? (``pip install git+https://github.com/wmayner/pyphi.git@develop``?)

**Comment by fischerdom** [comment]
Sorry, I missed this mail. Yes it was with the branch. I did an
uninstall/install before running the experiments. Now I just returned to
the last working version.



Schöne Grüße
Dominik Fischer

2017-09-14 16:36 GMT+02:00 Bo Marchman <notifications@github.com>:

**Comment by rlmv** [comment]
Ok, thanks for the report. Would you be willing to share the code that's causing the issue?

**Comment by rlmv** [comment]
This should be fixed in the both the 0.9.0 and 1.0.0 releases.
